name = "managedash"
main = "worker.js"
compatibility_date = "2024-11-01"

# ============================================
# ربط قاعدة بيانات KV (الجلسة الحية)
# ============================================
[[kv_namespaces]]
binding = "SESSION_KV"   # الاسم اللي تستعمله في الكود (مثلاً env.SESSION_KV)
id = "76ead9dff9344f20a6c49f682f11d0b5"

# ============================================
# المتغيرات العادية (غير سرية)
# ============================================
[vars]
GITHUB_OWNER = "bergham123"
GITHUB_REPO = "wtsc"
GITHUB_BRANCH = "main"
WORKFLOW_FILE = "send.yaml"
MESSAGES_PATH = "data/message.json"
CONTACTS_PATH = "data/accounts.json"
IMAGES_LIST_PATH = "data/images.json"          # 👈 هاد الصف جديد (كان ناقص)
IMAGES_DIR = "images"                      # 👈 هاد الصف جديد (مجلد الصور)
WORKER_URL = "https://managedash.velora.workers.dev"
