name = "wtsc"
main = "functions/_worker.js"   # إذا كنت تستخدم _worker.js، أو غيرها لـ functions/
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# متغيرات البيئة (ستُضاف أيضاً في لوحة Cloudflare)
[vars]
GITHUB_TOKEN = "your_token_here"
OWNER = "bergham123"
REPO = "wtsc"
# JWT_SECRET = "your_secret_here"

# إعدادات النشر
[build]
command = ""
cwd = ""
watch_dir = "dashboard"

[build.upload]
format = "modules"
